### ISSUE TITLE
isFull(final Collection<? extends Object> coll)

### ISSUE THREAD

**Issue by mrlFranchi** [mrlFranchi/VVT-Trabalho#71]
5 mutantes linhas 1481 1482 1487 1489

**Comment by joaolucasp** [comment]
void isFull() {
    assertThrows(NullPointerException.class, () -> CollectionUtils.isFull( null));
    assertEquals(false, CollectionUtils.isFull(List.of()));
   
    List<Integer> coll = new ArrayList<>(5);
    FixedSizeList<Integer> L = FixedSizeList.fixedSizeList(coll);

    assertEquals(true, CollectionUtils.isFull(L));

    coll.add(1);
    assertEquals(true, CollectionUtils.isFull(L));
  }

**Comment by mrlFranchi** [comment]
Falta mutante 1 na linha 1482, e 2 na linha 1487
