### ISSUE TITLE
collate(final Iterable<? extends O> a, final Iterable<? extends O> b,

### ISSUE THREAD

**Issue by mrlFranchi** [mrlFranchi/VVT-Trabalho#75]
9  Metodo na linha 1599

**Comment by joaolucasp** [comment]
reza a lenda que é só adicionar:

@Test
  void collate() {
    List<Integer> l = Arrays.asList(1, 5, 2, 1, 0);
    List<Integer> v = Arrays.asList(10, 25, 1, 7, 7);

    assertThrows(NullPointerException.class, () -> CollectionUtils.collate(l, null));
    assertThrows(NullPointerException.class, () -> CollectionUtils.collate(null, v));
    assertThrows(NullPointerException.class, () -> CollectionUtils.collate(l, v, null));
    assertNotEquals(Arrays.asList(1, 2, 3), CollectionUtils.collate(l, v, false));
    assertNotEquals(Arrays.asList(1, 2, 3), CollectionUtils.collate(l, v, true));
    assertEquals(Arrays.asList(1, 5, 2, 1, 0, 10, 25, 1, 7, 7), CollectionUtils.collate(l, v));
  }

**Comment by mrlFranchi** [comment]
Não deu não ... e eu tinha contado os mutantes errados
