### ISSUE TITLE
retainAll(final Iterable<E> collection

### ISSUE THREAD

**Issue by mrlFranchi** [mrlFranchi/VVT-Trabalho#76]
2 utantes lnhas 1729 1733

**Comment by joaolucasp** [comment]
agora 100%

void retainAll() {
	  List<Integer> L = Arrays.asList(1, 2, 3);
	  List<Integer> R = new ArrayList<>();
	  
	  Equator<Integer> equator = new Equator<>() {
	        @Override
	        public boolean equate(Integer o1, Integer o2) {
	          return o1.equals(o2);
	        }

	        @Override
	        public int hash(Integer o) {
	          return o.hashCode();
	        }

	 };
	 
	  assertEquals(List.of(), CollectionUtils.retainAll(L, R));
	  assertEquals(List.of(), CollectionUtils.retainAll(L, R, equator));
	  R.add(1);
	  assertEquals(List.of(1), CollectionUtils.retainAll(L, R, equator));
  }
