### ISSUE TITLE
removeAll(final Collection<E> collection, final Collection<?> remove)

### ISSUE THREAD

**Issue by mrlFranchi** [mrlFranchi/VVT-Trabalho#77]
1 mutante linha 1760

**Comment by joaolucasp** [comment]
reza a lenda que é só adicionar

@Test
  void removeAll1() {
	  List<Integer> l =  Arrays.asList(1,2,3,4);
	  List<Integer> t =  Arrays.asList(1,2,3);
	  
	  assertNotEquals(CollectionUtils.removeAll(l, t), null);
  }
