### ISSUE TITLE
removeAll(final Iterable<E> collection

### ISSUE THREAD

**Issue by mrlFranchi** [mrlFranchi/VVT-Trabalho#78]
2 mutantes linhas 1805 1809

**Comment by joaolucasp** [comment]
agora 100%

 void removeAll() {
    List<Integer> L = Arrays.asList(1,2,3,4);
    List<Integer> R = Arrays.asList(1,2);
    List<Integer> V = Arrays.asList(5,6);

    assertEquals(Arrays.asList(3,4),CollectionUtils.removeAll(L, R));
    
    Equator<Integer> equator = new Equator<>() {
        @Override
        public boolean equate(Integer o1, Integer o2) {
          return o1.equals(o2);
        }

        @Override
        public int hash(Integer o) {
          return o.hashCode();
        }

      };
      
      assertEquals(Arrays.asList(1,2,3,4), CollectionUtils.removeAll(L, V, equator));
      assertEquals(Arrays.asList(3,4), CollectionUtils.removeAll(L, R, equator));
  }
